server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ITManagerDevices
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true